### ISSUE TITLE
frame on stopped event

### ISSUE THREAD

**Issue by gil-n** [taskcluster/gdb-js#3]
hi,

can you add the full frame object on stopped event?
at the moment you add a partial frame, eg:
 event.thread = new Thread(toInt(thread), {
            frame: new Frame({
              file: data.frame.fullname,
              line: toInt(data.frame.line)
            }),

I need additional info on the frame like the func name ...args and address can be nice to.
something like: 
event.frame = data.frame

**Comment by baygeldin** [comment]
Sure, it is possible. It will require extending the Frame object though.
At the moment it is possible to listen to raw events:
```javascript
gdb.on('exec', (e) => {
  if (e.state === 'stopped') {
    console.log(e.data.frame) // e.data is the raw JSON representation of GDB/MI message 
  }
})
```
Will it work for you for now?

**Comment by gil-n** [comment]
Yes it will work, i just wonder which option will give a better performance.
1. add the Frame on the the stopped event
2. listen to the exec event
3. request the stack list on the the stopped event to get the frame.

Thanks

**Comment by baygeldin** [comment]
The first and the second options are essentially the same in terms of performance (the first one is just a convenient wrapper tbh). The third one will require an additional command to be executed in gdb though, so it is slower. However, I think that the slowdown will be almost negligible, so it is up to you.

**Comment by gil-n** [comment]
Excellent, i'll use the exec option. 
Thanks a lot.
